# Dependencies
markdown:         redcarpet
highlighter:      pygments

# Permalinks
permalink:        pretty
relative_permalinks: true

# Setup
title:            Research Notes 
tagline:          'A Jekyll theme'
description:      'Focusing on Coq'
url:              http://researchnote.github.io
baseurl:          /

author:
  name:           'Mark Otto'
  url:            http://researchnote.github.io

paginate:         5

# Custom vars
version:          2.1.0

github:
  repo:           https://github.com/poole/hyde
